version: '3.8'

services: 
  mongo:    
    image: mongo:latest  
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: abcdb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:     
      - "27017:27017"    
    volumes:
      - vmongo:/data/db
      - type: bind
        source: /Users/mac/emvol
        target: /data/db
    networks:
      nnode:
        aliases:
          - mongoa

  emongo:
    image: mongo-express:latest
    container_name: emongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo 
      ME_CONFIG_MONGODB_ADMINUSERNAME: abcuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: abcpass
      ME_CONFIG_BASICAUTH_USERNAME: euser
      ME_CONFIG_BASICAUTH_PASSWORD: epass
    networks:
      nnode:
        aliases:
          - emongo
    volumes:
      - type: bind
        source: /Users/mac/emvol
        target: /data/db

  node:     
    build: ./node/mern/backend
    image: nodeimage1
    container_name: node
    ports:     
      - "8080:8080"  
    depends_on:   
      - mongo
    volumes:
      - vnode:/usr/src/app
    networks:
      nnode:
        aliases:
          - nodea
    

volumes:
  vnode: {}
  vmongo: {}

networks:
  nnode: 
    driver: bridge 

